export const NOTIFICATION_TYPES = [
  "NEW_PRODUCT_ADDED",
  "EMAIL_VERIFIED",
  "PHONE_VERIFIED",
  "COURSE_UPDATED",
  "REFUND_PROCESSED",
  "QR_CODE_GENERATED",
  "TICKETS_ALMOST_SOLD_OUT",
  "CONTACT_FORM_REPLY",
  "QUERY_FORM_REPLY",
  "CLASS_SCHEDULE_CHANGED",
  "NEW_ANNOUNCEMENT",
] as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
